language: python

sudo: false
dist: trusty

matrix:
    include:
        - &pylint
          env: RUN_PYLINT=true
          python: '3.4'
          addons: { apt: { packages: [] } }
          cache: {}
        - python: '3.4'
        - python: '3.5'
        - python: 'nightly'
    allow_failures:
        - python: 'nightly'
        - *pylint
    fast_finish: true

cache:
    apt: true
    pip: true
    ccache: true
    directories:
        - $TRAVIS_BUILD_DIR/pyqt

addons:
    apt:
        packages:
            - libblas-dev
            - liblapack-dev
            - gfortran
            - libqt4-dev
            - xvfb

before_install:
    - set -e  # fail on any error
    - source $TRAVIS_BUILD_DIR/.travis/util.sh


install:
    - source $TRAVIS_BUILD_DIR/.travis/stage_install.sh
    # Update pip to be able to install wheel dependencies
    - pip install -U pip wheel
    - pip install -e .

script: python setup.py test